### ISSUE TITLE
Return back to same page after forced logout / login

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#1003]
When data.all forces a logout you may have been on a page like https://DOMAIN/console/shares/tcfa7xyh and naturally you may want to log back in to the same page you were without having to find your way to the same share.. It would be nice if after re-logging in data.all took you to the same place that you were just visiting.

**Comment by noah-paige** [comment]
I like the idea of the above - may want to have some further discussion about if this should be default behavior by data.all or should think only be the behavior if re-login is within a certain time range since last force logout

This functionality of saving the location and handling redirect back to the previous page is actually already existing as part of reAuthentication (only when handling reAuth on query operations) - so can look to re-use the same functionality there and can be a quick implementation

**Comment by zsaltys** [comment]
@noah-paige @dlpzx @anmolsgandhi was this not completed already?

**Comment by noah-paige** [comment]
Yes I believe implemented in https://github.com/data-dot-all/dataall/pull/1094 and addressed also in https://github.com/data-dot-all/dataall/issues/1092

I will close both issues as complete - thanks @zsaltys

**Comment by noah-paige** [comment]
closing as completed in #1094
