### ISSUE TITLE
Pipeline Failure: DeployFrontEnd Stage - cannot import name 'is_s3express_bucket' from 'botocore.utils'

### ISSUE THREAD

**Issue by shivalkarrahul** [data-dot-all/dataall#1051]
### Describe the bug

All of a sudden, the DeployFrontEnd Stage started failing with the following error.

Error: ImportError: cannot import name 'is_s3express_bucket' from 'botocore.utils' (/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/botocore/utils.py)

Data-dot-all version: v2.0.0

### How to Reproduce

```
Simply execute the pipeline, the DeployFrontEnd will fail
```

### Expected behavior

The pipeline should run as usual

### Screenshots

<img width="1072" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/24cd1b9f-69ae-4cc5-9b5d-0bb86bd30f3e">

<img width="1272" alt="image" src="https://github.com/data-dot-all/dataall/assets/19208841/a28f51ef-185e-4f64-843d-06a874a01f33">

### OS

build_image=codebuild.LinuxBuildImage.AMAZON_LINUX_2_4

### Python version

3.9

### AWS data.all version

v2.0.0

### Additional context

The pipeline was working fine till Friday and suddenly started failing.

Log File:
[error-logs.txt](https://github.com/data-dot-all/dataall/files/14235834/error-logs.txt)

**Comment by dlpzx** [comment]
This issue does not affect the current version of data.all 2.2, but it is relevant for versions < 2.2 (versions prior to this [PR](https://github.com/data-dot-all/dataall/pull/889)). That is, because the issue impacts CodeBuild images that use Python 3.9. 

In any case, if for any reason you are using Python 3.9 in the CodeBuild stages of your data.all pipeline, this [PR](https://github.com/data-dot-all/dataall/pull/1054) opened by @anandsumit2000 solves the problem. 🚀
