### ISSUE TITLE
Automatic code formatting

### ISSUE THREAD

**Issue by petrkalos** [data-dot-all/dataall#1076]
**Is your feature request related to a problem? Please describe.**
Inevitable when we are working on new features we are touching a lot of files and our IDEs might reformat code unrelated to our change. This is not ideal because it makes reviewing much more difficult (hard to find the important changes) but also might introduce unnecessary conflicts. 

**Describe the solution you'd like**
I suggest we introduce automated formatting (i.e using black)
* Run it as part of CI/CD
* Urge contributors to use it as a pre-commit hook

**Describe alternatives you've considered**
The other alternative is to ask for people to refrain from doing such changes but this relies on good intentions it won't always work.

**Comment by jaidisido** [comment]
In favour, however I recommend using [Ruff](https://docs.astral.sh/ruff/) instead of black as it's significantly faster and covers most linters in one. We used to use black within aws-sdk-pandas but recently made the switch to [ruff](https://github.com/aws/aws-sdk-pandas/blob/main/pyproject.toml#L141) and are happy customers
