### ISSUE TITLE
Data.all allows 2 or more datasets with same s3 bucket

### ISSUE THREAD

**Issue by anushka-singh** [data-dot-all/dataall#1278]
### Describe the bug

Data.all allows importing 2 or more datasets with the same bucket name. This could confusion for a producer since they would have different shares on different datasets but on the same bucket. It could also lead to inconsistent behavior since bucket policy could be updated by different shares at the same time.

### How to Reproduce

Import dataset1 with s3 bucket: s3bucketName
Import dataset2 with s3 bucket: s3BucketName

Both will be imported successfully and stack creation will also go through. 

### Expected behavior

You should not be allowed to import more than one dataset with a s3 bucket name that has already been imported before. 

### OS

Mac

### Python version

3.9

### AWS data.all version

2.4

### Additional context

@zsaltys

**Comment by dlpzx** [comment]
Thanks @anushka-singh for opening an issue! This behavior was allowed because there was an scenario in which the same bucket hosted multiple Glue databases. Some customers did not care about the S3 resources but only wanted to share the Glue resources. This is a workaround, but it should not be the norm. I have tagged the issue accordingly and we will pick it up when  possible.

**Comment by noah-paige** [comment]
cc: @zsaltys - we will plan to add this validation when creating a new dataset so no 2 datasets can use the same bucket moving forward
