### ISSUE TITLE
Inviting Team to Organization Sliders Disabled

### ISSUE THREAD

**Issue by noah-paige** [data-dot-all/dataall#373]
### Describe the bug

When an organization admin is inviting a team to the organization there are 2 slides for Organization Permissions that the invite can define:
1. 'Link environments to this organization' permissions
2. 'Invite teams to this organization' permissions

Both of these sliders are enabled by default and are not editable. 

When a team is invited to an org it has the permissions to link environments (1 above) but is not able to invite additional teams (2 above).

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

N/A

### Python version

N/A

### AWS data.all version

1.4

**Comment by dlpzx** [comment]
Hi @noah-paige, this is the intended behavior. If a team is invited to the Organization it means that it can perform all actions at the Organization-level = link environments and invite other teams to the orga. To disable this permissions you just need to remove the team from the Organization. 

Maybe the confusion came because the organization groups multiple environments and it can be assumed that "in order to work in environments I need to be invited to the organization" but that is NOT true. Any team can be invited to an environment without the need of it to be in the Organization-invited-teams.

We can work on UI enhancements to avoid this misunderstanding, so happy to hear your thoughts on how you would picture the whole user experience

**Comment by noah-paige** [comment]
Hi @dlpzx - the above makes sense to me but when I am testing locally and inviting another team to my Organization that invited team cannot then invite additional teams to the org.

Also, I think some confusion from my end is coming because on the frontend when I try to invite a team to my organization the sliders shown below are not editable and I am not seeing the second slider (Invite Teams) permission to be granted

Is this the designed behavior and/or are you able to reproduce what I am seeing? 
 
![Screenshot 2023-03-16 at 12 25 43 PM](https://user-images.githubusercontent.com/69586985/225686872-f51804f6-f7a3-466e-8e99-bfc07369ed97.png)
