### ISSUE TITLE
Error in Monitoring tab in Admin Settings

### ISSUE THREAD

**Issue by kasturmp** [data-dot-all/dataall#374]
### Describe the bug

It is not a functional error but happens every time when switching between monitoring and teams tab:
```
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::1111111111111:assumed-role/dataall-dev-graphql-role/dataall-dev-graphql is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::1111111111111:role/dataallPivotRole

```

### How to Reproduce

It is not a functional error but happens every time when switching between monitoring and teams tab:

### Screenshots

```
An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::1111111111111:assumed-role/dataall-dev-graphql-role/dataall-dev-graphql is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::1111111111111:role/dataallPivotRole

```

### OS

All

### Python version

3.1

### AWS data.all version

1.4,1.3

**Comment by dlpzx** [comment]
Hi @kasturmp, thanks for raising the issue. I renamed it and replaced your images as they contained AWS Account IDs. 

From the log I think that the issue is on the Monitoring tab that is trying to fetch some parameter in the infra account assuming the pivotRole, which does not exist. It only affects users using the Monitoring feature, I'll have a look to confirm the hypothesis and I'll try to work on the fix

**Comment by dlpzx** [comment]
@SofiaSazonova @noah-paige @petrkalos @anmolsgandhi ---> Instead of fixing this issue, why don't we implement a better monitoring experience as part of 2.5?
