### ISSUE TITLE
On a fresh data.all installation creating a pipeline with development strategy "CDK trunk" fails

### ISSUE THREAD

**Issue by wolfit** [data-dot-all/dataall#490]
### Describe the bug

Documentation: "ddk bootstrap -e cicd" needed also in non-multi environment setups. 
See pipelines.md

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```

### OS

Mac

### Python version

3.8

### AWS data.all version

1.5.3

**Comment by dlpzx** [comment]
Hi @wolfit thanks for raising the issue and yes I think I also got into that situation once. Let me confirm it and we will update the docs.

**Comment by noah-paige** [comment]
Hi @wolfit - thank you for opening up this issue. We have since updated the way data.all creates Pipelines to move away from the DDK CLI (deprecated) and make it easier for data.all Users to use Pipelines - refer to the updated `dataall/documentation/userguide/docs/pipelines.md`

If you want to take a deeper dive into the code changes - have a look at this [PR ](https://github.com/data-dot-all/dataall/pull/866)

**Comment by anmolsgandhi** [comment]
Hello, Thank @noah-paige for the response, Closing this issue as it seems that the issue would be resolved with enhancement in the associated PR. @wolfit Feel free to reopen if you have any questions or need more assistance
