### ISSUE TITLE
dbmigration is failing

### ISSUE THREAD

**Issue by bliu9881** [data-dot-all/dataall#789]
I am facing similar problem with the issue #217 
but I am using default value for quality gate. Could you please help to what/how to trouble shoot this?

IN_PROGRESS
--
711 | running migration
712 | IN_PROGRESS
713 | running migration
714 | IN_PROGRESS
715 | running migration
716 | FAILED
717 |  
718 | [Container] 2023/10/12 17:41:02 Running command if [ "$(jq -r .builds[0].buildStatus codebuild-output.json)" = "FAILED" ]; then echo "Failed";  cat codebuild-output.json; exit -1; fi
719 | Failed
720 | {
721 | "builds": [
722 | {
723 | "id": "bcm-dev-dbmigration:dd2730ea-8d30-46e9-ab69-063c967bc17b",
724 | "arn": "arn:aws:codebuild:us-east-2:758968765298:build/bcm-dev-dbmigration:dd2730ea-8d30-46e9-ab69-063c967bc17b",
725 | "buildNumber": 2,

**Comment by dlpzx** [comment]
Hi @bliu9881, thanks for opening an issue and sorry for the late response. Your issue is in the migration stage right? The migration stage allows data.all to automatically perform changes in the tables of the RDS database. Because we are modifying the RDS database, the migration scripts are executed in the deployment account. In other words, from the tooling account pipeline Codebuild stage we trigger a second Codebuild stage in the deployment account.

The logs that you are showing there are the logs from the first Codebuild stage (tooling), which as you probably noticed, do not provide much insights. To investigate the issue we need the logs from the second Codebuild stage. You need to go into the deployment account > CodeBuild > Codebuils projects and search for "migration". You should find a project like the following (probably with a different name). Can you copy/past the logs of the last build of that project?

![image](https://github.com/awslabs/aws-dataall/assets/71252798/8d02a05e-1f6e-4a97-a259-42bc606bf1bd)

**Comment by anmolsgandhi** [comment]
Hello, it seems there hasn’t been any recent activity on this issue. Is there anything more we can do to assist, or shall we consider closing it if the problem has been resolved? Thanks
