### ISSUE TITLE
the table uploaded is empty 

### ISSUE THREAD

**Issue by zhudayong1987** [data-dot-all/dataall#906]
### Describe the bug

when i upload children_csv file，but the preview is empty

### How to Reproduce

```
*P.S. Please do not attach files as it's considered a security risk. Add code snippets directly in the message body as much as possible.*
```
1：upload csv file
2：check the data in preview

### OS

win10

### Python version

python3.9

### AWS data.all version

newest

**Comment by dlpzx** [comment]
hi @zhudayong1987, welcome to the project! 

Uploading a file from the data.all UI, uploads the file in S3. The preview functionality applies to data.all tables (Glue Tables under the hood), it does not query the csv file directly, it queries the tables. So if there is an error, it probably is in the table creation.

So my first question is: has the dataset crawler been run? If so, does any table appear in the `data` tab?
![Screenshot 2023-12-12 at 09 23 16](https://github.com/awslabs/aws-dataall/assets/71252798/edaf693d-7f75-4a6b-8d0e-34ca91caf3b4)

I am guessing that the table was created because in your issue you are able to go to the preview tab which is accessible from the table. The most typical error that causes the preview to be empty is that the crawler did not identified the table correctly. Crawlers are easy to use and fast, but they might fail if the folder/files structure contains multiple file schemas or if the schemas contain any special field.

To check the table, you can run the exact same query directly from Athena. Go to the environment (of the dataset) > Teams tab > click on the dataset owner team AWS access button. This link redirects you to AWS where you can go to Athena or Glue to check the table schema.

![Screenshot 2023-12-12 at 09 28 21](https://github.com/awslabs/aws-dataall/assets/71252798/e9a58567-1d24-4c27-b67d-245437679b59)

Please, update us with any progress (or no progress) :)

**Comment by dlpzx** [comment]
Hi @zhudayong1987 are you still facing issues?
