### ISSUE TITLE
Consumer IAM role updates can get wiped out by CloudFormation

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#922]
When we request shared access using an IAM role, data.all updates the role with necessary permissions. While this is a useful feature, it poses a problem. Consumer roles are usually managed by tools like CloudFormation and are not created or controlled by data.all. If a consumer role is managed through CloudFormation, any modifications to its policies will overwrite changes made to it by data.all.

This can result in the following scenario:

1) a request is made for access using an IAM consumer role
2) access is approved
3) access is verified as working and a production application is deployed with the new role
4) production engineering updates the IAM role using cloudformation being unaware that data.all has made modifications to it's policy
5) cloudformation wipes out any changes made by data.all
6) production application looses access causing an outage

With this enhancement we want to figure out how to prevent such issues. In our specific enterprise we do not want data.all to update IAM roles for us because we cannot not allow our devops to continue managing them via CloudFormation. One way to do that would be to have a feature flag that disables data.all from modifying consumer IAM roles itself.

However this would not solve the whole problem because then users would be left confused if they were granted access and it simply doesn't work because the IAM role does not have access and they would be left to figure out what modifications they need to make. 

The simplest thing we could do is provide clear UI instructions how the IAM role needs to be modified to grant it access. We could do this by providing JSON policy statements and a CloudFormation snippet that can be copy pasted. 

Another idea would be to create a policy for the IAM consumer role when it gets registered on the environment. Then all shares will always update this policy by triggering a change on the environment stack. We would then provide clear instructions during share registration that this policy will need to be attached to the role by the user itself using CloudFormation etc or if they wants they can tick a checkbox and let data.all do it for them (in case they don't manage roles with CF). We could even go further and show a validation check on each consumer role if it has the policy attached and if it doesn't then do not allow to use that consumer role in share requests.

This last idea would guarantee that a consumer role cannot be used if it's not properly configured and it would allow data.all to manage the permissions the IAM role has without the danger of CF wiping out changes data.all has made.

**Comment by zsaltys** [comment]
@noah-paige @dlpzx Please review. I would like to prioritize this highly for 2.3 as priority nr 3 after unique shares fix (prio 2) and ability to fix permissions on datasets (prio 1).

**Comment by dlpzx** [comment]
Hi @zsaltys thanks for opening the issue! We have thought about this issue offline and here is our summary and proposal

In short, the goal is:

* To introduce a configurable feature that allows external management of IAM roles and their data policies
* While ensuring that S3-Bucket and S3-AccessPoint sharing still works and is easy to use by users

## Design

For any of the options below, we will first need to implement the feature flag that you mentioned:

* configuration parameter in the data_sharing module manage_iam_roles = True/False
* (current implementation) For `manage_iam_roles = True` data sharing updates the IAM roles inline policies. It assumes that data.all now manages the IAM role. The only changes needed are some optional additional documentation.
* (new implementation) For `manage_iam_roles = False`
    * data sharing does NOT update the IAM roles inline policies. Instead, it will implement one of the following options.
    * (optional) add checks for “valid” IAM policy to ensure share integrity

### Option 1: Copy/paste policy from UI + Users manually update the IAM policy of the role

1. In data.all UI plots the IAM policy statement that needs to be added to the IAM role. It can easily be copied to the clipboard.
2. Users go to their IAM role and manually modify the role policies adding the piece of policy copied to the clipboard
3. (optional) add the policy statements to IaC creation of the IAM role

PROS: easy to implement from data.all point of view. Data.all does not perform any actions on the role, all responsibilities fall on the IAM role external managers

CONS: very error prone due to manual changes. Risk of overwriting other shares or worse, of adding too open permissions. Difficult to integrate as IaC.



### Option 2: Create IAM Managed Policy +  Users attach the managed policy to the role

1. In data.all backend, the data sharing task creates an IAM Managed policy for the requester when the share is processed
2. Users go to their IAM role and manually attach the created Managed policy to the role
3. (optional) add the policy to IaC creation of the IAM role

PROS: easy to implement from data.all point of view. Less error prone (no code writing). Easy to integrate with IaC (conditional on existence of policy. Only needs to be attached once)

CONS: Part of the IAM role permissions are managed by data.all. Number of managed policies: per IAM role we will create 1 Managed Policy for Bucket share and 1 for access points.

**Comment by TejasRGitHub** [comment]
@dlpzx , even I think option 2 would be better to implement this feature. 

1. In case the share is revoked and the share for that dataset no longer exists, then this managed IAM role should be deleted . In that case, while or before revoking another set of instructions would have to be provided to remove the role from IaC ( if its used there ) 
2. Could this feature implemented on a per dataset share basis. As in if someone doesn't wants their consumption roles to be managed by data.all then they select NO option on the share request modal , etc otherwise they select YES and it is managed by data.all instead of making it a feature on the whole dataset.  Pros - makes dataset sharing and permission handling flexible . Cons - Might increase complexity and take time to implement.

**Comment by SofiaSazonova** [comment]
@dlpzx  What if...?
To all roles, created by IaC we can add tag = 'cfn managed' or vice-versa. When data.all updates the role, for IaC managed we can store info in database: inline policy with arn-P is added to the role named Role_R.
So, after the update, we can restore permissions. 

OR
If we don't have tons of IaC managed roles, we can use tags with role-name to restore the permissions. 

Am I thinking the right way?

**Comment by dlpzx** [comment]
Good morning team! Let me address your comments:
1. Removing policies after revoke (@TejasRGitHub ) --> in the revoke, data.all deletes the IAM policy. I just tested it and by deleting the policy, it is automatically removed from the IAM role. In the IAM role definition, we should attach the IAM policies for sharing adding a CFN condition that checks for its existence. I am not sure this addresses your question, let me know.
2. Yes, @TejasRGitHub managing role-updates per share might be a little more complicated, but if you think it is what end-users will need, then we can implement it in the module as: `manage_iam_role` = `FULL` for data.all full management (current), `OPTIONAL` (per sharing), `EXTERNALLY`(all roles handled externally) (with better names :) )
3. Yes, @TejasRGitHub imported IAM roles have the same challenge and we should treat them the same as consumption roles in this design
4. @SofiaSazonova 2 things to take into account: first a maximum of 2 policies can be attached for sharing to the IAM roles (one for bucket sharing and one for access point sharing). Secondly, the policies will be as independent from the role as possible, so I was thinking of managed policies instead of inline policies. Regarding your idea, luckily, data.all created IAM roles are tagged with the tag `dataall`=`True`, so we could do the distinction. It would allow us to check if a share is healthy by checking the non `dataall` tagged roles' policies and verify that the required "sharing" policies are attached. I think we could do it without any additional info in RDS, at the end we just need to check if max 2 IAM policies are present in the IAM role. We could implement a "reactive" correction of the IAM roles on an schedule or on-demand by showing the health status to the users in the UI. In my opinion it is a good complimentary feature that ensures customers completed the external steps for the share to work.

**Comment by TejasRGitHub** [comment]
Hi @dlpzx , 

For 1. are you saying that the CF template while attaching this IAM policy to that IAM role should add a CFN condition to check weather the policy exists or not and that this will make sure if that even when the policy is removed it wouldn't cause any problems
2. Yes, I believe it will be complicated . For this change , for now, I don't mind just introducing a module config and do it for all shares. But I would like to hear @zsaltys your opinion on this.

**Comment by SofiaSazonova** [comment]
@TejasRGitHub  @dlpzx 
 As soon as. role is added to data.all scope (invited), we can create two managed policies:
   `role_name_s3_bucket_share` and `role_name_s3_endpoint_share`
We can modify this policies, when the object is shared or the access is revoked. 
1. These policies will always exist
2. There are only two of them, so we won't hit the limit until there are to many statements inside them.
We can delete this policies, when the correspondent role is removed from data.all scope.
![Untitled Diagram drawio](https://github.com/data-dot-all/dataall/assets/1146495/cb2369dd-4e7a-43f0-8f45-1028d49add66)

**Comment by SofiaSazonova** [comment]
I propose to split the solution of the problem in two steps. They do not exclude but complete each other.
For both this steps I suggest to get rid of inline policies and use only managed policies. 

### Step1.  Create special managed policies for each consumer role

For this step we don’t need the feature flag yet.
When the role is imported into data.all as a consumer role, two managed policies are created:
`role_name_s3_bucket_share`  and ` role_name_s3_endpoint_share. `This policies are attached to the consumer role when it’s imported. 

_**To think about**: we can use only one managed policy, because currently bucket and endpoint access is granted together. But with two of them we will have more flexibility._

If the role is managed by customer via Infrastructure as Code (IaC), customer will have to add this policies to their role definition. This policies are to be managed by data.all deployment account and we can guarantee, that the are exist as long as the correspondent consumer role is in data.all scope.

_**To think about:** it’s not possible to create a role without statements or resources in it. So, we should consider to give the consumer role some initial permissions._
When the object is shared with consumer role, data.all appends resources to the policy statement (or create a policy statement). When the access is revoked, resources are deleted from policy statement. 
_**To think about:** Each policy update creates a new version. It’s possible to have up to 5 versions, so we need to decide, how many recent version we want to store. I think. it’s better to store just the last one and delete the previous after update.
**To think about:** The size of each managed policy can't exceed 6,144 characters. IAM doesn't count white space when calculating the size of a policy against this limit._

![managed policies share](https://github.com/data-dot-all/dataall/assets/1146495/c6912403-6d6d-4345-af9f-67b56ed04f0b)

What problems it solves:
1. Managed policies are not overwritten by update of consumer role via IaC.  No outages.
2. All resources can be managed with only two managed policies. We are restricted with 10 (20) per role. Think about policy size.

What problems we still have:
1. Customer themselves is responsible for role management and attachment of the right policy.
2. We need to insure, that customer uses the right policy with the right role and doesn’t mix them.



### Step 2. Monitor the imported policies in customer account. Share-health check.

Now we can introduce the feature flag `manage_iam_roles = True` . For managed roles data.all will do the following. 
Using the trusted role in customer account data.all deploys monitoring stack containing (highlighted with green colour on the picture below):

1. Event Bridge rule, that monitors Cloud Trail events regarding role changes ( this mechanism can be expanded in future).
2. Lambda, triggered by this rule, that is trusted to send events into deployment account’s event bus. 

In deployment account data.all can process the events with the following logic, if role was modified:

1. Check the shares this role participates in (query RDS). [Optional]
2. If shares are active, check role permissions. [Optional]
3. Reattach the policies, if they are lost. [Main purpose]

_**To think about:** how we can limit data.all access to customers Cloudtrail to let it only see the events about consumer roles?_

![monitoring of customer acc](https://github.com/data-dot-all/dataall/assets/1146495/ae7755f8-5c8d-4b6f-92e2-249e910bf8d6)

What problems it solves:

1. Fully data.all managed consumer role.
2. Customer is not required to have permissions to attach policies.
3. The shares are restored almost immediately after role update. No outages, but no strong consistency.
4. All resources can be managed with only two managed policies. We are restricted with 10 (20) per role. _**Think about policy size.**_

What problems we still have:

1. Data.all have additional information flow, which can be 
    1. inappropriate  for the customer
    2. raise new issue for AppSec review

**Comment by zsaltys** [comment]
@SofiaSazonova your last proposed design mostly makes sense to me. I have some observations.

Your proposal almost matches my original proposal. I agree that policies should be created when they are registered on the environment. It's a good catch that we need to grant some initial _empty_ permissions. I do however think that data.all should ask users if they want data.all to update their role and attach a policy to it as this could be convenient to users who don't use IaC. And for those who do use IaC we provide instructions how to attach a policy. However how do we actually do that and when? We need to figure during which UI flow we ask the user to make a choice? One option is during consumer role registration on the environment - the problem with that is that at that point the managed policies are not yet created. So we could let users tick a checkbox during registration to let data.all update the role but we can't solve the manual attachment on that UI. To solve manual attachment we could validate during creation of a share to validate that the IAM role actually has policies attached and if it doesn't then we tell the user hey you haven't attached these policies to your role and you can't use this role for this share.

I propose that we meet on call to discuss this as that might be easier than trying to understand one another over comments.

As for step 2 I think we should leave that for @noah-paige as I believe he plans on working on re-applying broken permissions to buckets and KMS policies.. and I think IAM roles should go into that same design too.. Or even a separate issue.

**Comment by dlpzx** [comment]
@SofiaSazonova nice design. Here are some additional questions:
- Are the IAM policies going to be created as IaC in the environment stacks or are we going to create them through SDKs?
- Similarly, in step 2, are we going to create the eventbridge stack as part of the environment stack?
