### ISSUE TITLE
Issue with enable_pivot_role_auto_create When Deploying Multiple Environments in a Single AWS Account

### ISSUE THREAD

**Issue by asifma** [data-dot-all/dataall#936]
### Describe the bug

We have encountered a challenge when deploying multiple environments within a single AWS account, specifically related to the enable_pivot_role_auto_create setting. Currently, when this setting is set to True, it leads to an unexpected behavior that hinders the successful deployment of multiple environments.

The issue stems from the handling of the pivot role in the backend/dataall/core/environment/cdk/environment_stack.py file. Here's a snippet for reference:

`

        pivot_role_as_part_of_environment_stack = ParameterStoreManager.get_parameter_value(
            region=os.getenv('AWS_REGION', 'eu-west-1'),
            parameter_path=f"/dataall/{os.getenv('envname', 'local')}/pivotRole/enablePivotRoleAutoCreate"
        )
        self.create_pivot_role = True if pivot_role_as_part_of_environment_stack == "True" else False
        self.engine = self.get_engine()

        self._environment = self.get_target(target_uri=target_uri)

        self.environment_groups: [EnvironmentGroup] = self.get_environment_groups(
            self.engine, environment=self._environment
        )

        self.environment_admins_group: EnvironmentGroup = self.get_environment_admins_group(
            self.engine, self._environment
        )

        # Create or import Pivot role
        if self.create_pivot_role is True:
            config = {
                'roleName': self.pivot_role_name,
                'accountId': self.dataall_central_account,
                'externalId': self.external_id,
                'resourcePrefix': self._environment.resourcePrefix,
                'environmentUri': self._environment.environmentUri
            }
            pivot_role_stack = PivotRole(self, 'PivotRoleStack', config)
            self.pivot_role = iam.Role.from_role_arn(
                self,
                f'PivotRole{self._environment.environmentUri}',
                pivot_role_stack.pivot_role.role_arn,
            )
        else:
            self.pivot_role = iam.Role.from_role_arn(
                self,
                f'PivotRole{self._environment.environmentUri}',
                f'arn:aws:iam::{self._environment.AwsAccountId}:role/{self.pivot_role_name}',
            )
`

### How to Reproduce

1. Set "enable_pivot_role_auto_create": true, in your DeploymentEnvironment in cdk.json
1. Create an environment
2. Try to create an additional environment in the same AWS Account
3. Second environment will fail to deploy, see CloudFormation in AWS Console for error

### Expected behavior

You should be able to create multiple environments in any region in the same AWS Account

### OS

linux

### Python version

3.11

### AWS data.all version

2.0

### Additional context

The current logic does not check if the role already exists, leading to the redundant creation of the nested pivot role stack which fails due to Role ARN already exists.

I suggest implementing logic to check for the existence of the role before attempting to create the nested pivot role stack.

**Comment by dlpzx** [comment]
Hi @asifma, thanks for opening this issue. I noticed that this limitation was also raised in https://github.com/awslabs/aws-dataall/issues/574. But we can continue the discussion here, as the code is more up-to-date.

At first it looks like an easy fix: just check if the IAM role exists and skip if it does not exist. The problem (which you already faced) is that that implementation only handles the environment creation but not the update. On a stack update the environment stack will detect that the pivot role exists and will delete it from the stack.

Another way of implementing this is by using an SSM parameter. In the environment stack:
1. check if the pivot role IAM role exists
2. If IAM role DOES NOT exist ---> create pivot role and SSM parameter `resourceprefix/...../environmentUri/pivotRole`
3. If IAM role EXIST, check if an SSM parameter `resourceprefix/...../environmentUri/pivotRole` exists in the environment region. 
    - 3.1. If SSM parameter DOES NOT exist ---> do NOT create pivot role and SSM parameter
    - 3.2. If SSM parameter EXIST --->  create pivot role and SSM parameter `resourceprefix/...../environmentUri/pivotRole`

This way we can handle the update of environment stack safely. This design needs to be verified with the latest changes in CloudFormation from re:invent. Maybe we got lucky and this issue was addressed with new launches :)

**Comment by sandeephs1** [comment]
Hello @dlpzx does "new launches" means v2.1.0 onwards

**Comment by dlpzx** [comment]
This issue has been added as stretch goal for 2.3

**Comment by anmolsgandhi** [comment]
The issue is in progress as part of the PR #1064 as it was added to v2.3 as a stretch goal but now will be moved to v2.4 release as we plan to start validation and testing for v2.3 release

**Comment by zsaltys** [comment]
@dlpzx https://github.com/data-dot-all/dataall/issues/779 does this not clash? I understand the user here for some reason wants to have multiple environments per AWS account within same REGION? Is that really something we want to support? When is this useful?

**Comment by sandeephs1** [comment]
Hello @dlpzx resolution to this issue is critical for us. Good that it is considered as part of v2.4.0. when is this release due?

**Comment by dlpzx** [comment]
@zsaltys the use case is not to have multiple environments in the same account same region, but to have multiple environments in the same account in different regions. Imagine that a user is using their AWS account in multiple regions. At the moment they can workaround data.all by using the manual pivot role and link the account one time for each region. However as explained in #1048 there is a limit in the amount of environments created.

@sandeephs1 thanks for commenting on the issue. I will continue working on it this week and next week. We have added more items to the scope of 2.4, so the official release might take some weeks. This is a high-priority issue that will be available in `main` before the release date in case you want to adopt it and test it before we release 2.4. Just bare in mind that features in `main` are still in a beta state

**Comment by dlpzx** [comment]
@sandeephs1 @zsaltys the design explained in this [PR](https://github.com/data-dot-all/dataall/pull/1064) is almost implemented and I will shortly start testing. It would be great to have your review on the design decisions

**Comment by sandeephs1** [comment]
@dlpzx Thanks for the clarification. We are enriching "Customer Onboarding" experience by completely automating it in our Data All. On priority, if we get solution to "multiple environments in different region" and "auto creation of pivotRole" would be helpful and ready to adopt and test before 2.4 release.

Issue #1048 (max policy size of 10240 bytes) can be delayed: because, total size applies to customer inline type. we are able to link around 9 to 10 Environments, which is Good at the Moment

**Comment by dlpzx** [comment]
Hi @sandeephs1 and team, the [PR](https://github.com/data-dot-all/dataall/pull/1064) for both this issues is being reviewed and tested. We need your input regarding some upgrade concerns that have arisen from the testing. The PR description is long, so if you want to skip to the most important topics, we specifically need your feedback on the bottom part of the description. In the section `Open issues, remarks and questions` there are some items not completed or with warnings. If you could please answer to those items, we will be able to take your needs into consideration. Bests!
