### ISSUE TITLE
Upgrade lambdas using v16 Node.js runtime

### ISSUE THREAD

**Issue by zsaltys** [data-dot-all/dataall#939]
Node.js v16 runtime is scheduled to be deprecated Jun 12, 2024.
Therefore we should upgrade all lambdas to Node.js 20 runtime.

**Comment by noah-paige** [comment]
Hi @zsaltys - for the above 2 lambdas:

- `dataall-prod-cloudfront-s-dataallprodhttpheadersre-GNuyR1QHIu8V`: This lambda gets created on `dataall/deploy/stacks/cloudfront.py` L451-484 and has specified Node Version 18 as of [this PR](https://github.com/awslabs/aws-dataall/pull/782/files) (included in data.all v2.1) Do you have the same?


- `dataall-prod-backend-stag-CognitoProviderprodframe-Ah0lxIGGFhlw`: The lambda function that backs the custom resource provider and is created at `dataall/deploy/stacks/cognito.py` L274. There is no explicit runtime property provided but when looking at my data.all deployment it defaults to Node.js 18

Strangely I have no node 14 runtimes for my lambda functions that deploy the latest data.all OS code

**Comment by zsaltys** [comment]
@noah-paige do you have any runtimes below 18? I wonder if there's an issue that new deployments do not update runtimes. Our version is still 2.0. Were the runtimes updated after 2.0 ?

**Comment by noah-paige** [comment]
Lambda Runtimes were updated in 2.1 ([PR](https://github.com/awslabs/aws-dataall/pull/782))

There should be no node 14 runtimes but there still are some node 16 ones from the way we handle auth on the userguide that will have to be updated in the near future

**Comment by zsaltys** [comment]
@noah-paige I repurposed the ticket to upgrade all lambda runtimes to v20. Thanks!

**Comment by noah-paige** [comment]
As of current data.all deployment - the only node16 runtimes are present because of the AuthAtEdge Serverless Application Repo we use to protect the static site userguide with Cognito IdP ([link to AuthAtEdge Repo](https://github.com/aws-samples/cloudfront-authorization-at-edge))

On the AuthAtEdge Repo they have a pending issue to upgrade Node before the end of support on June 12, 2024, meaning we could potentially wait for that upgrade to happen rather than prioritize for v2.3 of data.all

Also, depending on how we decide to implement userguide auth guard for external IdPs (no dependency on Cognito, i.e. [this issue](https://github.com/data-dot-all/dataall/issues/898)) we may remove the AuthAtEdge package altogether and create custom edge lambdas to handle auth piece for userguide

**Comment by noah-paige** [comment]
Because of the details mentioned in the above comment - this issue will be removed from v2.3 release and will be re-prioritized to be picked up at the same time as issue #872

**Comment by anmolsgandhi** [comment]
@noah-paige can this be closed ? i see its moved to Done in the backlog

**Comment by noah-paige** [comment]
@anmolsgandhi - need to update the `semanticVersion` of the AuthAtEdge application we currently use - this is a good call out as we need to update from v16 asap

Looking into migration path and will open a PR shortly if no blockers
