### ISSUE TITLE
Team remove / uninvite should have a pop-up for confirmation 

### ISSUE THREAD

**Issue by TejasRGitHub** [data-dot-all/dataall#942]
**Is your idea related to a problem? Please describe.**

When removing team from organization / environment there is no second confirmation if this action should be done. This can cause someone to remove the team unintentionally. 

**Describe the solution you'd like**

When removing teams from environment / organization , before the action is executed present a pop-up on the UI saying
" Are you sure  you want to remove the team " and then when the user confirms this it will be easily done. 
This is avoid any unintended team removals from the environment/ organization

**Comment by noah-paige** [comment]
Hi @TejasRGitHub - I think the above would be a nice enhancement to the UI to ensure no accidental deletes. Will add the above to our backlog and find some time to prioritize the above in a future release!

**Comment by weversonmuciarone** [comment]
We noticed the same few weeks back when a member of our team unintentionally removed an Admin team role from the environments / team. If the screen is small like a laptop the buttons will shrink and (-) remove option is very close to (aws) option. Our team member clicked in the (-) as he was trying to click (aws) and the env team was wiped out.

@noah-paige @dlpzx  since this has been requested back in Jan, is there a fix for this yet? 

Thanks.

**Comment by dlpzx** [comment]
Hi @weversonmuciarone we have added this item to the list of possible candidates for 2.5, which is a release focused on user experience, so it fits perfectly.

**Comment by weversonmuciarone** [comment]
Thanks.

**Comment by dlpzx** [comment]
completed
